[WIP]: Add ability to use paid maxmind service
flowkey/user-location pull request #2
Opened 2017-02-01 23:23 UTC by lightningboss

2017-02-05 19:49 UTC, nerdmed requested changes

2017-02-05 19:49 UTC, nerdmed commented on lib/getLocationForIpWithService.js
> +const userId = Meteor.settings.maxmind.userId;
unsafe access, why error if there are no settings or no maxmind namespace?

2017-02-05 19:49 UTC, nerdmed commented on lib/asyncHTTP.js
> +function asyncHTTP(url, method = 'GET', options = {}) {
why is this needed? can we use a fetch npm module? It should return a promise.
This function is only used once. I would suggest to just use a promise down there, or just use the callback to KIS 👍

2017-02-05 19:49 UTC, nerdmed commented on lib/getLocationForIpWithService.js
> +    service: 'country',
can i target the service?

2017-02-05 19:49 UTC, nerdmed commented on Readme.md
> +Meteor.call('UserLocation/getForIpWithService', ip, callback);
witch service? What do you think about making this clear: `loopUpWithMaxmind`or something similar: `getIpWithMaxmind`

2017-02-05 19:49 UTC, nerdmed commented on lib/getLocationForIpWithService.js
> +        if (!userId || !licenseKey) {
confused: thought this is the meteor userId - maybe we can name it maxmindUserId or something

2017-02-05 19:49 UTC, nerdmed commented on lib/getLocationForIpWithService.js
> +    service: 'country',
suggestion - make service an option with default: maxmindLookup({ service = 'country' }),

2017-02-05 19:49 UTC, nerdmed commented on lib/getUserIp.js
> +            asyncHTTP(GET_IP_API_ENDPOINT)
why is this needed? Only for development?

2017-02-05 19:49 UTC, nerdmed commented on lib/sanitizeResult.js
> +export function sanitizeServiceResult(result) {
which service? I would suggest to name it to make it clear

2017-02-05 19:49 UTC, nerdmed commented on lib/sanitizeResult.js
> +    return new Promise((resolve, reject) => {
why is this wrapped in a promise?

2017-03-17 17:53 UTC, lightningboss commented on lib/getLocationForIpWithMaxMind.js
> +            reject('You didn\'t provide userId or licenseKey for maxmind');
pass in error obj

2017-03-17 17:53 UTC, lightningboss commented on Readme.md
>  Meteor.call('UserLocation/getForIp', ip, callback) // IP lookup for any ip
getWithMaxMind

2017-05-22 09:57 UTC, nerdmed commented on lib/getLocationForIpLocal.js
> +import lookupIp from 'geoip-lite';
import geoIpLite.lookup()

2017-05-22 09:57 UTC, nerdmed commented on lib/getLocationForIpWithMaxMind.js
> +const maxMindSettings = _.defaults(meteorMaxMindSettings, defaultMaxMindSettings);
const maxMindSettings = {
...defaultMaxMindSettings
... meteorMaxMindSettings
}

2017-05-22 09:57 UTC, nerdmed commented on user-location.js
> +    Meteor.call('UserLocation/get', (err, res) => {
das hier in eigene function

2017-05-22 09:57 UTC, nerdmed commented on user-location.js
> +    Meteor.call('UserLocation/get', (err, res) => {
hier aufrufen

2017-05-22 09:57 UTC, nerdmed commented on user-location.js
> +    UserLocation.update(true);
die neue function hier direkt callen

2018-03-13 14:22 UTC, nerdmed approved these changes
lgtm

2018-03-13 14:22 UTC, merged